server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /products { proxy_pass http://product-service:4001; }
    location /categories { proxy_pass http://product-service:4001; }
    location /cart { proxy_pass http://product-service:4001; }
    location /orders { proxy_pass http://order-service:4002; }
    location /payments { proxy_pass http://order-service:4002; }
    location /auth { proxy_pass http://order-service:4002; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
